import type { BmcBlockId, LeanBlockId, Segment, SkillId } from "../types";

export interface BusinessModelPattern {
  id: string;
  name: string;
  emoji: string;
  description: string;
  howItMakesMoney: string;
  examples: string[];
  revenueType: "recurring" | "transactional" | "one-time";
  /** Monetization sentence appended to generated one-liners. */
  offer: string;
  defaults: {
    avgCheck: number; // ₽ per purchase
    purchasesPerMonth: number;
    grossMargin: number;
    monthlyChurn: number;
    cacMonthsOfRevenue: number; // CAC expressed in months of ARPU
  };
  scalability: number; // 1..5
  capital: number; // 1..5, 5 = needs lots of capital
  speedToRevenue: number; // 1..5, 5 = money from day one
  skills: SkillId[];
  segments: Segment[];
  keyMetrics: string[];
  risks: string[];
  lean: Partial<Record<LeanBlockId, string>>;
  bmc: Partial<Record<BmcBlockId, string>>;
}

export const BUSINESS_MODELS: BusinessModelPattern[] = [
  {
    id: "saas",
    name: "Подписка (SaaS)",
    emoji: "☁️",
    description: "Клиент платит ежемесячно или ежегодно за доступ к сервису.",
    howItMakesMoney: "Регулярные платежи за доступ; рост за счёт расширения тарифов и снижения оттока.",
    examples: ["amoCRM", "Notion", "Контур"],
    revenueType: "recurring",
    offer: "Монетизация: подписка от 2 990 ₽/мес.",
    defaults: { avgCheck: 2990, purchasesPerMonth: 1, grossMargin: 0.8, monthlyChurn: 0.04, cacMonthsOfRevenue: 4 },
    scalability: 5,
    capital: 2,
    speedToRevenue: 2,
    skills: ["tech", "product", "sales"],
    segments: ["b2b", "b2c"],
    keyMetrics: ["MRR", "отток (churn)", "LTV/CAC", "NRR", "активация"],
    risks: ["Высокий отток в первые месяцы", "Долгий цикл продаж в B2B", "Копирование функциональности конкурентами"],
    lean: {
      revenueStreams: "Ежемесячная подписка (3 тарифа), годовая оплата со скидкой, платные интеграции",
      costStructure: "Разработка, хостинг, поддержка клиентов, маркетинг и продажи",
      keyMetrics: "MRR, отток, активация в первую неделю, LTV/CAC, NPS",
      channels: "Контент-маркетинг и SEO, контекстная реклама, партнёрские интеграции, холодные продажи",
    },
    bmc: {
      revenueStreams: "Подписка по тарифам, годовые планы, допродажи",
      costStructure: "ФОТ разработки, инфраструктура, привлечение клиентов",
      customerRelationships: "Самообслуживание + онбординг, база знаний, customer success для крупных клиентов",
      keyActivities: "Разработка продукта, онбординг клиентов, удержание",
      keyResources: "Платформа, команда разработки, данные клиентов",
      keyPartners: "Интеграторы, облачные провайдеры, платёжные сервисы",
    },
  },
  {
    id: "marketplace",
    name: "Маркетплейс (комиссия)",
    emoji: "🏬",
    description: "Платформа соединяет продавцов и покупателей и берёт комиссию со сделки.",
    howItMakesMoney: "Комиссия 10–25% с каждой сделки, платное продвижение для продавцов.",
    examples: ["Авито", "Профи.ру", "Airbnb"],
    revenueType: "transactional",
    offer: "Монетизация: комиссия 15% с каждой сделки.",
    defaults: { avgCheck: 600, purchasesPerMonth: 1.5, grossMargin: 0.75, monthlyChurn: 0.08, cacMonthsOfRevenue: 3 },
    scalability: 5,
    capital: 3,
    speedToRevenue: 2,
    skills: ["marketing", "ops", "tech"],
    segments: ["b2c", "b2b"],
    keyMetrics: ["GMV", "take rate", "ликвидность (доля запросов, закрытых сделкой)", "повторные сделки"],
    risks: ["Проблема курицы и яйца на старте", "Уход сделок «в обход» платформы", "Сложное управление качеством"],
    lean: {
      revenueStreams: "Комиссия со сделки, платное продвижение для исполнителей, подписка для профессионалов",
      costStructure: "Привлечение обеих сторон, модерация и поддержка, разработка платформы",
      keyMetrics: "GMV, take rate, ликвидность, время до первой сделки, повторные сделки",
      channels: "Performance-маркетинг, SEO по категориям, сарафанное радио, партнёрства",
    },
    bmc: {
      revenueStreams: "Комиссия с GMV, продвижение, подписка для продавцов",
      costStructure: "Маркетинг двух сторон, модерация, разработка",
      customerRelationships: "Самообслуживание, рейтинги и отзывы, гарантия сделки",
      keyActivities: "Привлечение продавцов и покупателей, контроль качества, матчинг",
      keyResources: "База продавцов и покупателей, рейтинги, платформа",
      keyPartners: "Платёжные провайдеры, службы доставки, страховщики",
    },
  },
  {
    id: "freemium",
    name: "Freemium",
    emoji: "🎁",
    description: "Базовая версия бесплатна, расширенные функции — платные.",
    howItMakesMoney: "Конверсия 2–5% бесплатных пользователей в платных.",
    examples: ["Яндекс Диск", "Canva", "Duolingo"],
    revenueType: "recurring",
    offer: "Монетизация: бесплатная базовая версия и премиум от 399 ₽/мес.",
    defaults: { avgCheck: 399, purchasesPerMonth: 1, grossMargin: 0.85, monthlyChurn: 0.06, cacMonthsOfRevenue: 3 },
    scalability: 5,
    capital: 3,
    speedToRevenue: 1,
    skills: ["tech", "product", "marketing"],
    segments: ["b2c"],
    keyMetrics: ["MAU", "конверсия в платных", "удержание D30", "ARPPU"],
    risks: ["Низкая конверсия в платных", "Расходы на бесплатных пользователей", "Нужна большая аудитория"],
    lean: {
      revenueStreams: "Премиум-подписка, разовые покупки внутри продукта",
      costStructure: "Инфраструктура для бесплатных пользователей, разработка, маркетинг",
      keyMetrics: "MAU, удержание D1/D7/D30, конверсия free→paid, ARPPU",
      channels: "Вирусность, магазины приложений, контент, реферальная программа",
    },
    bmc: {
      revenueStreams: "Премиум-подписка, внутриигровые/внутрипродуктовые покупки",
      customerRelationships: "Полное самообслуживание, сообщество",
      keyActivities: "Развитие продукта, рост аудитории, оптимизация конверсии",
    },
  },
  {
    id: "d2c",
    name: "D2C-бренд",
    emoji: "🧴",
    description: "Собственный бренд продукта, продажи напрямую покупателю онлайн и через маркетплейсы.",
    howItMakesMoney: "Наценка на собственный продукт; повторные покупки и подписка на расходники.",
    examples: ["Splat", "12 Storeez", "Zuzu"],
    revenueType: "transactional",
    offer: "Монетизация: продажа продукции со средним чеком около 2 500 ₽.",
    defaults: { avgCheck: 2500, purchasesPerMonth: 0.4, grossMargin: 0.55, monthlyChurn: 0.12, cacMonthsOfRevenue: 1.2 },
    scalability: 4,
    capital: 4,
    speedToRevenue: 4,
    skills: ["marketing", "design", "ops"],
    segments: ["b2c"],
    keyMetrics: ["средний чек", "повторные покупки", "ROMI", "оборачиваемость запасов"],
    risks: ["Замороженные деньги в запасах", "Рост стоимости рекламы", "Копирование продукта"],
    lean: {
      revenueStreams: "Продажа продукции через свой сайт и маркетплейсы, наборы и подписка на расходники",
      costStructure: "Себестоимость производства, логистика и хранение, комиссии маркетплейсов, реклама",
      keyMetrics: "Средний чек, доля повторных покупок, ROMI, маржа после рекламы",
      channels: "Маркетплейсы, соцсети и блогеры, собственный интернет-магазин",
    },
    bmc: {
      revenueStreams: "Продажа продукции, подписка на расходники",
      keyPartners: "Контрактное производство, фулфилмент, маркетплейсы, блогеры",
      keyActivities: "Разработка продукта, брендинг, маркетинг, управление запасами",
      keyResources: "Бренд, рецептура/дизайн, сообщество покупателей",
    },
  },
  {
    id: "service",
    name: "Сервисная компания / агентство",
    emoji: "🧰",
    description: "Компания оказывает услуги силами своей команды.",
    howItMakesMoney: "Оплата за проект или за час работы специалистов.",
    examples: ["digital-агентства", "клининговые компании", "консалтинг"],
    revenueType: "transactional",
    offer: "Монетизация: оплата за проект от 50 000 ₽.",
    defaults: { avgCheck: 50000, purchasesPerMonth: 0.3, grossMargin: 0.4, monthlyChurn: 0.1, cacMonthsOfRevenue: 1 },
    scalability: 2,
    capital: 1,
    speedToRevenue: 5,
    skills: ["sales", "ops", "domain"],
    segments: ["b2b", "b2c"],
    keyMetrics: ["загрузка специалистов", "маржа проекта", "доля повторных клиентов", "NPS"],
    risks: ["Рост ограничен наймом", "Зависимость от ключевых людей", "Кассовые разрывы из-за отсрочек"],
    lean: {
      revenueStreams: "Оплата за проект, абонентское обслуживание, срочные работы с наценкой",
      costStructure: "ФОТ специалистов, продажи, офис и инструменты",
      keyMetrics: "Загрузка команды, маржинальность проекта, повторные заказы, NPS",
      channels: "Рекомендации, личные продажи, кейсы и контент, профильные площадки",
    },
    bmc: {
      revenueStreams: "Проекты, абонентское обслуживание",
      keyActivities: "Продажи, оказание услуг, контроль качества",
      keyResources: "Команда специалистов, экспертиза, кейсы",
      customerRelationships: "Персональный менеджер, долгосрочные отношения",
    },
  },
  {
    id: "productized",
    name: "Упакованная услуга (productized service)",
    emoji: "📦",
    description: "Услуга, упакованная как продукт: фиксированный объём, цена и срок.",
    howItMakesMoney: "Фиксированные пакеты по подписке или за результат, стандартизированный процесс.",
    examples: ["бухгалтерия по подписке", "дизайн по подписке", "SEO-пакеты"],
    revenueType: "recurring",
    offer: "Монетизация: фиксированные пакеты по подписке от 15 000 ₽/мес.",
    defaults: { avgCheck: 15000, purchasesPerMonth: 1, grossMargin: 0.5, monthlyChurn: 0.05, cacMonthsOfRevenue: 1.5 },
    scalability: 3,
    capital: 1,
    speedToRevenue: 5,
    skills: ["ops", "sales", "domain"],
    segments: ["b2b"],
    keyMetrics: ["MRR", "себестоимость пакета", "отток", "время выполнения"],
    risks: ["Расползание объёма работ", "Зависимость от исполнителей", "Ценовая конкуренция"],
    lean: {
      revenueStreams: "Ежемесячные пакеты (Базовый / Стандарт / Про), разовые доп. услуги",
      costStructure: "Исполнители, инструменты автоматизации, продажи",
      keyMetrics: "MRR, отток, себестоимость пакета, SLA",
      channels: "Партнёрские рекомендации, контент, холодные продажи, маркетплейсы услуг",
    },
    bmc: {
      revenueStreams: "Подписка на пакеты услуг",
      keyActivities: "Стандартизация и автоматизация процессов, продажи",
    },
  },
  {
    id: "lead_gen",
    name: "Агрегатор / лидогенерация",
    emoji: "🧲",
    description: "Сервис собирает спрос и продаёт заявки или клиентов бизнесу.",
    howItMakesMoney: "Оплата за заявку (CPL), за действие (CPA) или подписка на поток заявок.",
    examples: ["Сравни.ру", "Банки.ру", "агрегаторы услуг"],
    revenueType: "transactional",
    offer: "Монетизация: бизнес платит за каждого привлечённого клиента.",
    defaults: { avgCheck: 1500, purchasesPerMonth: 4, grossMargin: 0.6, monthlyChurn: 0.06, cacMonthsOfRevenue: 2 },
    scalability: 4,
    capital: 2,
    speedToRevenue: 3,
    skills: ["marketing", "sales", "tech"],
    segments: ["b2b", "b2b2c"],
    keyMetrics: ["стоимость лида", "цена продажи лида", "качество лидов", "число партнёров"],
    risks: ["Зависимость от рекламных платформ", "Споры о качестве лидов", "Партнёры уходят в прямой маркетинг"],
    lean: {
      revenueStreams: "Оплата за заявку/клиента, подписка партнёров, размещение",
      costStructure: "Закупка трафика, контент и SEO, продажи партнёрам",
      keyMetrics: "Стоимость лида, маржа на лиде, доля принятых лидов, число активных партнёров",
      channels: "SEO, контекстная реклама, сравнительный контент",
    },
    bmc: { keyPartners: "Компании-покупатели лидов, рекламные платформы" },
  },
  {
    id: "franchise",
    name: "Франшиза",
    emoji: "🏪",
    description: "Тиражирование отработанной модели через партнёров-франчайзи.",
    howItMakesMoney: "Паушальный взнос + роялти 3–7% от выручки партнёров.",
    examples: ["Додо Пицца", "Кофе Хауз", "детские клубы"],
    revenueType: "recurring",
    offer: "Монетизация: паушальный взнос и роялти от выручки партнёров.",
    defaults: { avgCheck: 40000, purchasesPerMonth: 1, grossMargin: 0.7, monthlyChurn: 0.015, cacMonthsOfRevenue: 6 },
    scalability: 4,
    capital: 3,
    speedToRevenue: 2,
    skills: ["ops", "sales", "finance"],
    segments: ["b2b"],
    keyMetrics: ["число точек", "выручка точки", "окупаемость точки", "роялти"],
    risks: ["Сначала нужна прибыльная собственная точка", "Контроль качества партнёров", "Юридическая сложность"],
    lean: {
      revenueStreams: "Паушальный взнос, роялти, маркетинговый сбор, поставки",
      costStructure: "Поддержка партнёров, обучение, бренд-маркетинг, юристы",
      keyMetrics: "Число точек, выручка и окупаемость точки, отток франчайзи",
      channels: "Каталоги франшиз, выставки, рекомендации действующих партнёров",
    },
    bmc: { keyActivities: "Отбор и обучение партнёров, стандарты, маркетинг бренда" },
  },
  {
    id: "rental",
    name: "Аренда и шеринг",
    emoji: "🔑",
    description: "Доступ к вещи или оборудованию вместо владения.",
    howItMakesMoney: "Плата за время использования; актив окупается многократной сдачей.",
    examples: ["каршеринг", "прокат инструмента", "аренда детских товаров"],
    revenueType: "transactional",
    offer: "Монетизация: почасовая и посуточная аренда.",
    defaults: { avgCheck: 1200, purchasesPerMonth: 1.2, grossMargin: 0.6, monthlyChurn: 0.15, cacMonthsOfRevenue: 1 },
    scalability: 3,
    capital: 5,
    speedToRevenue: 3,
    skills: ["ops", "finance"],
    segments: ["b2c", "b2b"],
    keyMetrics: ["загрузка актива", "окупаемость единицы", "износ и ремонт"],
    risks: ["Высокие капитальные затраты", "Порча и кражи", "Сезонность"],
    lean: {
      revenueStreams: "Почасовая/посуточная аренда, страховка, доставка",
      costStructure: "Закупка и обслуживание активов, хранение, логистика",
      keyMetrics: "Загрузка актива, выручка на единицу, срок окупаемости единицы",
      channels: "Локальная реклама, агрегаторы аренды, партнёрства",
    },
    bmc: { keyResources: "Парк активов, система бронирования, склад" },
  },
  {
    id: "pay_per_use",
    name: "Оплата за использование",
    emoji: "⏱️",
    description: "Клиент платит за фактическое потребление: запросы, минуты, единицы.",
    howItMakesMoney: "Тариф за единицу потребления; выручка растёт вместе с клиентом.",
    examples: ["облачные сервисы", "API-платформы", "SMS-рассылки"],
    revenueType: "recurring",
    offer: "Монетизация: оплата только за фактическое использование.",
    defaults: { avgCheck: 5000, purchasesPerMonth: 1, grossMargin: 0.65, monthlyChurn: 0.04, cacMonthsOfRevenue: 3 },
    scalability: 5,
    capital: 3,
    speedToRevenue: 3,
    skills: ["tech", "product"],
    segments: ["b2b"],
    keyMetrics: ["объём потребления", "NRR", "маржа на единицу"],
    risks: ["Непредсказуемая выручка", "Ценовые войны", "Себестоимость инфраструктуры"],
    lean: {
      revenueStreams: "Оплата за единицу потребления, пакеты объёма со скидкой",
      costStructure: "Инфраструктура, разработка, поддержка",
      keyMetrics: "Потребление на клиента, NRR, маржа на единицу",
      channels: "Документация и сообщество разработчиков, партнёры, прямые продажи",
    },
    bmc: {},
  },
  {
    id: "razor_blades",
    name: "Бритва и лезвия",
    emoji: "🪒",
    description: "Основной продукт дешёвый, зарабатываем на расходниках и сервисе.",
    howItMakesMoney: "Низкая цена устройства, высокая маржа на регулярных расходниках.",
    examples: ["кофемашины с капсулами", "принтеры", "фильтры для воды"],
    revenueType: "recurring",
    offer: "Монетизация: недорогой стартовый комплект и подписка на расходники.",
    defaults: { avgCheck: 1500, purchasesPerMonth: 1, grossMargin: 0.6, monthlyChurn: 0.05, cacMonthsOfRevenue: 3 },
    scalability: 4,
    capital: 4,
    speedToRevenue: 3,
    skills: ["ops", "marketing", "design"],
    segments: ["b2c", "b2b"],
    keyMetrics: ["доля покупающих расходники", "маржа расходников", "окупаемость устройства"],
    risks: ["Неоригинальные расходники конкурентов", "Субсидирование устройства", "Логистика"],
    lean: {
      revenueStreams: "Стартовый комплект по себестоимости, подписка на расходники, сервис",
      costStructure: "Производство устройств, логистика, маркетинг",
      keyMetrics: "Доля клиентов, покупающих расходники; средний срок жизни клиента",
      channels: "Маркетплейсы, партнёрская розница, собственный магазин",
    },
    bmc: {},
  },
  {
    id: "community",
    name: "Сообщество / членство",
    emoji: "👥",
    description: "Платное сообщество с контентом, нетворкингом и мероприятиями.",
    howItMakesMoney: "Членские взносы, платные мероприятия, спонсорство.",
    examples: ["бизнес-клубы", "профессиональные сообщества", "клубы по интересам"],
    revenueType: "recurring",
    offer: "Монетизация: членство от 1 500 ₽/мес.",
    defaults: { avgCheck: 1500, purchasesPerMonth: 1, grossMargin: 0.75, monthlyChurn: 0.07, cacMonthsOfRevenue: 2 },
    scalability: 3,
    capital: 1,
    speedToRevenue: 4,
    skills: ["content", "marketing"],
    segments: ["b2c", "b2b"],
    keyMetrics: ["число участников", "вовлечённость", "отток", "доход на участника"],
    risks: ["Зависимость от лидера сообщества", "Снижение вовлечённости", "Сложно масштабировать качество"],
    lean: {
      revenueStreams: "Членские взносы, платные события, спонсорство, партнёрские предложения",
      costStructure: "Модерация и комьюнити-менеджмент, контент, мероприятия",
      keyMetrics: "Активные участники, доля вовлечённых, отток, NPS",
      channels: "Личный бренд основателя, рекомендации участников, контент",
    },
    bmc: {},
  },
  {
    id: "courses",
    name: "Обучение и курсы",
    emoji: "📚",
    description: "Платные образовательные программы онлайн или офлайн.",
    howItMakesMoney: "Продажа курсов, рассрочка, корпоративные программы, повторные продукты.",
    examples: ["онлайн-школы", "корпоративное обучение", "интенсивы"],
    revenueType: "one-time",
    offer: "Монетизация: курс стоимостью около 25 000 ₽.",
    defaults: { avgCheck: 25000, purchasesPerMonth: 1, grossMargin: 0.7, monthlyChurn: 1, cacMonthsOfRevenue: 0.35 },
    scalability: 4,
    capital: 2,
    speedToRevenue: 4,
    skills: ["content", "marketing", "domain"],
    segments: ["b2c", "b2b"],
    keyMetrics: ["стоимость заявки", "конверсия в оплату", "доходимость", "повторные покупки"],
    risks: ["Высокая стоимость привлечения", "Низкая доходимость", "Регуляторика образовательной деятельности"],
    lean: {
      revenueStreams: "Продажа курсов, рассрочка, корпоративные группы, продвинутые программы",
      costStructure: "Производство контента, преподаватели и кураторы, маркетинг",
      keyMetrics: "Стоимость лида, конверсия в оплату, доходимость, NPS, повторные покупки",
      channels: "Вебинары и автоворонки, блогеры, контент, рекомендации выпускников",
    },
    bmc: {},
  },
  {
    id: "advertising",
    name: "Рекламная модель",
    emoji: "📺",
    description: "Бесплатный контент или сервис, заработок на рекламодателях.",
    howItMakesMoney: "Продажа показов и интеграций рекламодателям.",
    examples: ["медиа", "бесплатные приложения", "блоги"],
    revenueType: "recurring",
    offer: "Монетизация: бесплатно для пользователей, доход от рекламодателей.",
    defaults: { avgCheck: 25, purchasesPerMonth: 1, grossMargin: 0.85, monthlyChurn: 0.1, cacMonthsOfRevenue: 4 },
    scalability: 5,
    capital: 3,
    speedToRevenue: 1,
    skills: ["content", "marketing", "tech"],
    segments: ["b2c"],
    keyMetrics: ["MAU", "ARPU от рекламы", "время в продукте", "CPM"],
    risks: ["Нужна огромная аудитория", "Зависимость от рекламного рынка", "Блокировщики рекламы"],
    lean: {
      revenueStreams: "Медийная реклама, нативные интеграции, спецпроекты",
      costStructure: "Контент, разработка, продвижение",
      keyMetrics: "MAU, время в продукте, CPM, ARPU",
      channels: "SEO, соцсети, вирусный контент",
    },
    bmc: {},
  },
  {
    id: "b2b2c",
    name: "White-label / B2B2C",
    emoji: "🤝",
    description: "Продукт продаётся конечным пользователям через крупных партнёров под их брендом.",
    howItMakesMoney: "Лицензия, revenue share или оплата за пользователя партнёра.",
    examples: ["страхование в приложениях банков", "сервисы в экосистемах", "white-label-приложения"],
    revenueType: "recurring",
    offer: "Монетизация: продажа через партнёров под их брендом, оплата за активного пользователя.",
    defaults: { avgCheck: 120000, purchasesPerMonth: 1, grossMargin: 0.7, monthlyChurn: 0.02, cacMonthsOfRevenue: 6 },
    scalability: 4,
    capital: 3,
    speedToRevenue: 1,
    skills: ["sales", "tech", "domain"],
    segments: ["b2b2c", "b2b"],
    keyMetrics: ["число партнёров", "пользователи через партнёров", "доход на партнёра"],
    risks: ["Долгие сделки с корпорациями", "Зависимость от нескольких партнёров", "Слабый собственный бренд"],
    lean: {
      revenueStreams: "Лицензия, revenue share, оплата за активного пользователя",
      costStructure: "Интеграции, корпоративные продажи, поддержка партнёров",
      keyMetrics: "Число партнёров, активация пользователей партнёра, доход на партнёра",
      channels: "Корпоративные продажи, отраслевые мероприятия, рекомендации",
    },
    bmc: {},
  },
];

export function getModel(id: string | undefined): BusinessModelPattern | undefined {
  return BUSINESS_MODELS.find((m) => m.id === id);
}
